
SET search_path TO public;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'estado_cliente_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.estado_cliente_enum AS ENUM ('activo', 'inactivo', 'bloqueado');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'rol_usuario_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.rol_usuario_enum AS ENUM ('ADMIN', 'OPERADOR', 'CONSULTA');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'estado_espacio_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.estado_espacio_enum AS ENUM ('disponible', 'reservado', 'ocupado', 'mantenimiento', 'bloqueado');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'estado_contrato_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.estado_contrato_enum AS ENUM ('ACTIVO', 'PAUSADO', 'TERMINADO', 'CANCELADO');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'tipo_ceremonia_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.tipo_ceremonia_enum AS ENUM ('FUNERAL', 'CREMACION', 'VISITA');
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_type t
        JOIN pg_namespace n ON n.oid = t.typnamespace
        WHERE t.typname = 'estado_ceremonia_enum'
          AND n.nspname = 'public'
    ) THEN
        CREATE TYPE public.estado_ceremonia_enum AS ENUM ('PROGRAMADA', 'CONFIRMADA', 'COMPLETADA', 'CANCELADA');
    END IF;
END $$;

-- 1. CRÍTICO: Crear PRIMERO la tabla perfiles_usuarios porque todas las demás dependen de ella
CREATE TABLE IF NOT EXISTS perfiles_usuarios (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    rol public.rol_usuario_enum NOT NULL DEFAULT 'OPERADOR',
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    updated_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

-- 2. Ahora sí podemos crear clientes
CREATE TABLE IF NOT EXISTS clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,
    rut VARCHAR(12) NOT NULL UNIQUE,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    telefono VARCHAR(30),
    email VARCHAR(150) UNIQUE,
    direccion TEXT,
    estado public.estado_cliente_enum NOT NULL DEFAULT 'activo',
    created_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    updated_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

-- 3. Crear espacios
CREATE TABLE IF NOT EXISTS espacios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) UNIQUE,
    sector VARCHAR(80) NOT NULL,
    tipo VARCHAR(60) NOT NULL,
    capacidad INTEGER NOT NULL DEFAULT 1,
    estado public.estado_espacio_enum NOT NULL DEFAULT 'disponible',
    georreferenciacion TEXT,
    descripcion TEXT,
    created_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    updated_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0
);

-- 4. Crear contratos (depende de clientes, espacios y perfiles_usuarios)
CREATE TABLE IF NOT EXISTS contratos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT,
    rut_cliente VARCHAR(12) NOT NULL,
    espacio_id BIGINT NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_termino DATE,
    monto_mensual NUMERIC(12,2) NOT NULL,
    estado public.estado_contrato_enum NOT NULL DEFAULT 'ACTIVO',
    observacion TEXT,
    created_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    updated_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_contratos_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT fk_contratos_espacio
        FOREIGN KEY (espacio_id)
        REFERENCES espacios(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_contrato_monto_positivo
        CHECK (monto_mensual > 0),
    CONSTRAINT chk_contrato_fechas
        CHECK (fecha_termino IS NULL OR fecha_termino >= fecha_inicio)
);

-- 5. Crear ceremonias (depende de contratos, clientes, espacios y perfiles_usuarios)
CREATE TABLE IF NOT EXISTS ceremonias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT,
    contrato_id BIGINT,
    espacio_id BIGINT,
    tipo_ceremonia public.tipo_ceremonia_enum NOT NULL,
    fecha_hora TIMESTAMP NOT NULL,
    ubicacion VARCHAR(150) NOT NULL,
    estado public.estado_ceremonia_enum NOT NULL DEFAULT 'PROGRAMADA',
    responsable_usuario_id UUID,
    observacion TEXT,
    created_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    updated_by_user_id UUID REFERENCES perfiles_usuarios(id) ON DELETE SET NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_ceremonias_cliente
        FOREIGN KEY (cliente_id)
        REFERENCES clientes(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT fk_ceremonias_contrato
        FOREIGN KEY (contrato_id)
        REFERENCES contratos(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT fk_ceremonias_espacio
        FOREIGN KEY (espacio_id)
        REFERENCES espacios(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT fk_ceremonias_responsable
        FOREIGN KEY (responsable_usuario_id)
        REFERENCES perfiles_usuarios(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT chk_ceremonia_fecha_valida
        CHECK (fecha_hora > TIMESTAMP '2000-01-01 00:00:00')
);

-- 6. Crear historial de eventos
CREATE TABLE IF NOT EXISTS historial_eventos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entidad VARCHAR(80) NOT NULL,
    registro_id TEXT NOT NULL,
    accion VARCHAR(20) NOT NULL,
    detalle JSONB NOT NULL DEFAULT '{}'::jsonb,
    usuario_id UUID,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_historial_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES perfiles_usuarios(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);
