spring.application.name=bff-service

# Puerto del BFF para el Frontend
server.port=8080

# URLs de los microservicios internos
services.inventario.base-url=http://localhost:8082/api/espacios
services.contratos.base-url=http://localhost:8083/api/contratos
