spring.application.name=bff-service

# Puerto del BFF para el Frontend
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

# URLs de los microservicios internos
app.inventario.url=${APP_INVENTARIO_URL:http://localhost:8081}
app.programacion.url=${APP_PROGRAMACION_URL:http://localhost:8082}
app.contratos.url=${APP_CONTRATOS_URL:http://localhost:8083}
